# Generated by Django 5.0.3 on 2024-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docesal_be', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
