# Generated by Django 5.0.3 on 2024-05-28 12:47

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("docesal_be", "UserProfile")

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("docesal_be", "0003_userprofile"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
