# Generated by Django 5.0.3 on 2024-06-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docesal_be', '0008_product_product_was_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_was_bought',
        ),
    ]
