# Generated by Django 5.0.3 on 2024-06-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docesal_be', '0010_logentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
